cmake_minimum_required(VERSION 3.24)

foreach(required_variable REPO_ROOT MODE)
    if(NOT DEFINED ${required_variable})
        message(FATAL_ERROR "${required_variable} is required")
    endif()
endforeach()

if(DEFINED LOCK_FILE)
    set(TGCLI_DEPENDENCY_LOCK_FILE "${LOCK_FILE}")
else()
    set(TGCLI_DEPENDENCY_LOCK_FILE "${REPO_ROOT}/release/dependencies.lock.json")
endif()
include("${REPO_ROOT}/cmake/DependencyLock.cmake")

if(MODE STREQUAL "lock")
    tgcli_assert_dependency_lock(cli11 "${EXPECTED_REF}")
elseif(MODE STREQUAL "script")
    tgcli_assert_tdlib_build_script("${EXPECTED_REF}" "${BUILD_SCRIPT_FILE}")
elseif(MODE STREQUAL "resolved")
    tgcli_assert_resolved_git_revision(cli11 "${SOURCE_DIRECTORY}" "${EXPECTED_REF}")
elseif(MODE STREQUAL "archive")
    set(TGCLI_RELEASE_ARCHIVE_MODE ON)
    set(CMAKE_BUILD_TYPE Release)
    set(FETCHCONTENT_FULLY_DISCONNECTED ON)
    tgcli_assert_resolved_git_revision(cli11 "${SOURCE_DIRECTORY}" "${EXPECTED_REF}")
elseif(MODE STREQUAL "no_archive")
    tgcli_assert_resolved_git_revision(cli11 "${SOURCE_DIRECTORY}" "${EXPECTED_REF}")
elseif(MODE STREQUAL "prefix")
    tgcli_assert_tdlib_prefix_provenance("${TD_PACKAGE_DIRECTORY}" "${EXPECTED_REF}")
else()
    message(FATAL_ERROR "Unknown dependency lock probe mode: ${MODE}")
endif()
