# Generated from docs/commands/public-command-registry.json. Do not edit.
complete -c tgcli -f -n '__fish_use_subcommand' -a 'account chat chats completion contact daemon doctor download fetch folder history listen login logout me msg raw read resolve saved schema search send session storage topic unread version wait-for'
complete -c tgcli -f -n '__fish_seen_subcommand_from account' -a 'add list remove show use'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat' -a 'archive ban demote info invite-link join kick leave mark-read members mute pin promote set-description set-permissions set-photo set-title unarchive unban unmute unpin'
complete -c tgcli -f -n '__fish_seen_subcommand_from contact' -a 'add block list remove search unblock'
complete -c tgcli -f -n '__fish_seen_subcommand_from daemon' -a 'restart run status stop'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder' -a 'add-chat create delete edit list remove-chat show'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg' -a 'delete edit forward get link pin react unpin'
complete -c tgcli -f -n '__fish_seen_subcommand_from saved' -a 'attach search tags'
complete -c tgcli -f -n '__fish_seen_subcommand_from session' -a 'list terminate'
complete -c tgcli -f -n '__fish_seen_subcommand_from storage' -a 'optimize stats'
complete -c tgcli -f -n '__fish_seen_subcommand_from topic' -a 'close create edit list reopen'
complete -c tgcli -f -n '__fish_seen_subcommand_from account; and __fish_seen_subcommand_from add' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from account; and __fish_seen_subcommand_from list' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from account; and __fish_seen_subcommand_from remove' -a '--json --verbose -v --no-color --keep-session --reassign-default --yes'
complete -c tgcli -f -n '__fish_seen_subcommand_from account; and __fish_seen_subcommand_from show' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from account; and __fish_seen_subcommand_from use' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from archive' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from ban' -a '--account --json --allow-write --dry-run --yes --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from demote' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from info' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from invite-link' -a '--account --json --allow-write --dry-run --yes --timeout --verbose -v --no-daemon --no-color --revoke'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from join' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from kick' -a '--account --json --allow-write --dry-run --yes --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from leave' -a '--account --json --allow-write --dry-run --yes --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from mark-read' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from members' -a '--account --json --timeout --cursor --verbose -v --no-daemon --no-color --admins --bots --query -n'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from mute' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --for'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from pin' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from promote' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --rights'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from set-description' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from set-permissions' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --allow --deny'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from set-photo' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --delete'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from set-title' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from unarchive' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from unban' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from unmute' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chat; and __fish_seen_subcommand_from unpin' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from chats' -a '--account --json --timeout --cursor --verbose -v --no-daemon --no-color --folder --archived --unread -n'
complete -c tgcli -f -n '__fish_seen_subcommand_from completion' -a '--json --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from contact; and __fish_seen_subcommand_from add' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --first-name --last-name --phone'
complete -c tgcli -f -n '__fish_seen_subcommand_from contact; and __fish_seen_subcommand_from block' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from contact; and __fish_seen_subcommand_from list' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from contact; and __fish_seen_subcommand_from remove' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from contact; and __fish_seen_subcommand_from search' -a '--account --json --timeout --verbose -v --no-daemon --no-color -n'
complete -c tgcli -f -n '__fish_seen_subcommand_from contact; and __fish_seen_subcommand_from unblock' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from restart' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from run' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from status' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from daemon; and __fish_seen_subcommand_from stop' -a '--json --verbose -v --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from doctor' -a '--json --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from download' -a '--account --json --timeout --verbose -v --no-daemon --no-color -O'
complete -c tgcli -f -n '__fish_seen_subcommand_from fetch' -a '--account --json --timeout --verbose -v --no-daemon --no-color --limit --all --since'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder; and __fish_seen_subcommand_from add-chat' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder; and __fish_seen_subcommand_from create' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --chat --icon --color-id'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder; and __fish_seen_subcommand_from delete' -a '--account --json --allow-write --dry-run --yes --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder; and __fish_seen_subcommand_from edit' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --name --icon --color-id --clear-icon'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder; and __fish_seen_subcommand_from list' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder; and __fish_seen_subcommand_from remove-chat' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from folder; and __fish_seen_subcommand_from show' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from history' -a '--account --json --timeout --cursor --verbose -v --no-daemon --no-color -n --before --since --until --topic --local'
complete -c tgcli -f -n '__fish_seen_subcommand_from listen' -a '--account --json --timeout --verbose -v --no-daemon --no-color --chat --types --count'
complete -c tgcli -f -n '__fish_seen_subcommand_from login' -a '--account --json --timeout --verbose -v --no-daemon --no-color --qr --bot'
complete -c tgcli -f -n '__fish_seen_subcommand_from logout' -a '--account --json --allow-write --dry-run --yes --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from me' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from delete' -a '--account --json --allow-write --dry-run --yes --timeout --idempotency-key --verbose -v --no-daemon --no-color --for-all'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from edit' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from forward' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --drop-author'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from get' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from link' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from pin' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from react' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --remove --big'
complete -c tgcli -f -n '__fish_seen_subcommand_from msg; and __fish_seen_subcommand_from unpin' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from raw' -a '- --account --json --allow-write --dry-run --yes --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from read' -a '--account --json --timeout --cursor --verbose -v --no-daemon --no-color -n --before --since --until --topic --local'
complete -c tgcli -f -n '__fish_seen_subcommand_from resolve' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from saved; and __fish_seen_subcommand_from attach' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --caption'
complete -c tgcli -f -n '__fish_seen_subcommand_from saved; and __fish_seen_subcommand_from search' -a '--account --json --timeout --cursor --verbose -v --no-daemon --no-color --tag -n'
complete -c tgcli -f -n '__fish_seen_subcommand_from saved; and __fish_seen_subcommand_from tags' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from schema' -a '--json --verbose -v --no-daemon --no-color --all'
complete -c tgcli -f -n '__fish_seen_subcommand_from search' -a '--account --json --timeout --cursor --verbose -v --no-daemon --no-color --chat --global --from --type -n'
complete -c tgcli -f -n '__fish_seen_subcommand_from send' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --md --html --reply-to --topic --silent --schedule'
complete -c tgcli -f -n '__fish_seen_subcommand_from session; and __fish_seen_subcommand_from list' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from session; and __fish_seen_subcommand_from terminate' -a '--account --json --allow-write --dry-run --yes --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from storage; and __fish_seen_subcommand_from optimize' -a '--account --json --allow-write --dry-run --yes --timeout --verbose -v --no-daemon --no-color --chat-limit'
complete -c tgcli -f -n '__fish_seen_subcommand_from storage; and __fish_seen_subcommand_from stats' -a '--account --json --timeout --verbose -v --no-daemon --no-color --chat-limit'
complete -c tgcli -f -n '__fish_seen_subcommand_from topic; and __fish_seen_subcommand_from close' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from topic; and __fish_seen_subcommand_from create' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color --icon-color --icon-custom-emoji-id'
complete -c tgcli -f -n '__fish_seen_subcommand_from topic; and __fish_seen_subcommand_from edit' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from topic; and __fish_seen_subcommand_from list' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from topic; and __fish_seen_subcommand_from reopen' -a '--account --json --allow-write --dry-run --timeout --idempotency-key --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from unread' -a '--account --json --timeout --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from version' -a '--json --verbose -v --no-daemon --no-color'
complete -c tgcli -f -n '__fish_seen_subcommand_from wait-for' -a '--account --json --timeout --verbose -v --no-daemon --no-color --chat --from --regex --after'
