include_guard(GLOBAL)

function(_tgcli_capture_cache_entry option prefix)
    if(DEFINED CACHE{${option}})
        set(${prefix}_EXISTS TRUE PARENT_SCOPE)
        foreach(property TYPE HELPSTRING VALUE)
            get_property(value CACHE "${option}" PROPERTY ${property})
            set(${prefix}_${property} "${value}" PARENT_SCOPE)
        endforeach()
    else()
        set(${prefix}_EXISTS FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_tgcli_restore_cache_entry option prefix)
    if(${prefix}_EXISTS)
        set(${option} "${${prefix}_VALUE}" CACHE STRING
            "${${prefix}_HELPSTRING}" FORCE)
        set_property(CACHE ${option} PROPERTY TYPE "${${prefix}_TYPE}")
        set_property(CACHE ${option} PROPERTY HELPSTRING "${${prefix}_HELPSTRING}")
        set_property(CACHE ${option} PROPERTY VALUE "${${prefix}_VALUE}")
    else()
        unset(${option} CACHE)
    endif()
endfunction()

function(tgcli_make_re2_available)
    foreach(option BUILD_SHARED_LIBS RE2_BUILD_TESTING USEPCRE)
        set(prefix tgcli_re2_cache_${option})
        _tgcli_capture_cache_entry(${option} ${prefix})
        set(${option} OFF CACHE BOOL "Private pinned RE2 option" FORCE)
        unset(${option})
    endforeach()

    FetchContent_MakeAvailable(re2)

    foreach(option BUILD_SHARED_LIBS RE2_BUILD_TESTING USEPCRE)
        _tgcli_restore_cache_entry(${option} tgcli_re2_cache_${option})
    endforeach()
    set(re2_SOURCE_DIR "${re2_SOURCE_DIR}" PARENT_SCOPE)
    set(re2_BINARY_DIR "${re2_BINARY_DIR}" PARENT_SCOPE)
endfunction()
